# Generated by Django 5.0.6 on 2024-05-26 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, upload_to='covers'),
        ),
        migrations.AddField(
            model_name='book',
            name='publication',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='book',
            name='translator',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
